Adjustments

diff --git a/.github/workflows/prepare-release.yaml b/.github/workflows/prepare-release.yaml
--- a/.github/workflows/prepare-release.yaml
+++ b/.github/workflows/prepare-release.yaml
@@ -20,29 +20,6 @@ name: Prepare release
 
 on:
   workflow_dispatch:
-    inputs:
-      reference:
-        required: true
-        type: choice
-        description: The reference (branch or tag) to use
-        options:
-          - develop
-          - deploy/fafbeta
-          - deploy/fafdevelop
-
-  workflow_call:
-    inputs:
-      reference:
-        required: true
-        type: string
-
-  pull_request:
-    paths:
-      - "changelog/snippets/*.md"
-
-  push:
-    branches:
-      - deploy/fafdevelop
 
 jobs:
 
@@ -57,14 +34,14 @@ jobs:
       # We check out the scripts separate because the branch that we use to
       # generate the changelog may not contain the scripts that we want to work with.
       - name: Checkout scripts
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           path: scripts
           sparse-checkout: |
             .github/workflows/scripts/bash
 
       - name: Checkout snippets
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           path: fa
           ref: ${{ inputs.reference }}
@@ -82,17 +59,17 @@ jobs:
 
 
   release-preparation:
-    name: Prepare patch changelog
+    name: Prepare files for patch
     runs-on: ubuntu-latest
     needs: verify
     steps:
 
       - name: Checkout FA repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           ssh-key: ${{ secrets.SSH_FAFOREVER_MACHINE_USER }}
           repository: FAForever/fa
-          ref: develop
+          ref: release-automation
 
       - name: Determine next patch version
         id: version
@@ -113,10 +90,13 @@ jobs:
 
       - name: Create branch
         run: |
+          if git ls-remote --heads origin "${{ steps.meta.outputs.branch }}"; then
+            echo "Branch '${{ steps.meta.outputs.branch }}' already exists. Aborting workflow."
+            exit 1
+          fi
           git checkout -b "${{ steps.meta.outputs.branch }}"
 
       - name: Create changelog post
-        continue-on-error: true
         working-directory: changelog/snippets
         run: |
           FILE="${{ github.workspace }}/docs/_posts/${{ steps.meta.outputs.date }}-${{ steps.version.outputs.version }}.md"
